#%RAML 0.8

title: TripPin service is a sample service for OData V4.
baseUri: http://services.odata.org/V4/(S(cnbm44wtbc1v5bgrlek5lpcc))/TripPinServiceRW

/Photos:
  get:
    description: Get entities from entity set Photos

  post:
    description: Post a new entity to entity set Photos

/Photos({Id}):
  get:
    description: Get entity from Photos by key

  patch:
    description: Update entity in entity set Photos

  delete:
    description: Delete entity in entity set Photos

/People:
  get:
    description: Get entities from entity set People

  post:
    description: Post a new entity to entity set People

/People('{UserName}'):
  get:
    description: Get entity from People by key

  patch:
    description: Update entity in entity set People

  delete:
    description: Delete entity in entity set People

  /Microsoft.OData.SampleService.Models.TripPin.GetFavoriteAirline():
    get:

  /Microsoft.OData.SampleService.Models.TripPin.GetFriendsTrips(userName='{userName}'):
    get:

  /Microsoft.OData.SampleService.Models.TripPin.ShareTrip:
    post:

/Airlines:
  get:
    description: Get entities from entity set Airlines

  post:
    description: Post a new entity to entity set Airlines

/Airlines('{AirlineCode}'):
  get:
    description: Get entity from Airlines by key

  patch:
    description: Update entity in entity set Airlines

  delete:
    description: Delete entity in entity set Airlines

/Airports:
  get:
    description: Get entities from entity set Airports

  post:
    description: Post a new entity to entity set Airports

/Airports('{IcaoCode}'):
  get:
    description: Get entity from Airports by key

  patch:
    description: Update entity in entity set Airports

  delete:
    description: Delete entity in entity set Airports

/GetNearestAirport(lat={lat},lon={lon}):
  get:
    description: Invoke function import GetNearestAirport

/ResetDataSource:
  post:
    description: Invoke action import ResetDataSource
